apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-azure
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-azure
  template:
    metadata:
      labels:
        app: spring-cloud-azure
    spec:
      containers:
      - name: spring-cloud-azure
        image: springregistry.azurecr.io/spring-cloud-azure:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1000Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
