apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-azure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-azure
  template:
    metadata:
      labels:
        app: spring-cloud-azure
    spec:
      containers:
      - name: spring-cloud-azure
        image: springregistry.azurecr.io/spring-cloud-azure:latest
        ports:
        - containerPort: 8080