apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-azure-service
spec:
  selector:
    app: spring-cloud-azure
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
